### ISSUE TITLE
adjust column heights 

### ISSUE THREAD

**Issue by TheMapSmith** [TheMapSmith/palettable-two#3]
the site test is working great! can you adjust the color columns so they stretch the width and height of the row?

**Comment by TheMapSmith** [comment]
#  🤖 

I'm glad the site is working well! To make the color columns stretch the width and height of the row, you can modify the CSS as follows:

Update the styles.css file with the following changes:


```css
body {
    font-family: Arial, sans-serif;
    background-color: #f8f9fa;
}

.row {
    height: 100px;
}

#palette .col {
    display: flex;
    justify-content: center;
    align-items: center;
    border: 1px solid #ddd;
    margin: 2px;
    color: white;
    font-weight: bold;
    flex-grow: 1;
    flex-basis: 0;
}
```

This will ensure that the color columns stretch to fill the available width and height within the row. The flex-grow: 1 and flex-basis: 0 properties tell each column to grow and fill the available space evenly.
