### ISSUE TITLE
lock color

### ISSUE THREAD

**Issue by TheMapSmith** [TheMapSmith/palettable-two#4]
please add a function that can lock a color when clicked and have it not regenerate when the button is pressed

**Comment by TheMapSmith** [comment]
# 🤖 

To add the functionality of locking a color when clicked and preventing it from regenerating when the button is pressed, we'll make the following modifications to your app.js file:

Add a locked attribute to the color element when it's clicked.
Modify the generatePalette() function to only generate new colors for unlocked elements.
Here's the updated code for the generatePalette() function and the click event listener:


```js
function generatePalette() {
    const palette = document.getElementById('palette');
    const colors = generateRandomColors(5);

    if (palette.childElementCount === 0) {
        colors.forEach((color, index) => {
            const col = document.createElement('div');
            col.className = 'col';
            col.style.backgroundColor = color;
            col.textContent = color;
            col.dataset.index = index;
            col.addEventListener('click', function () {
                if (col.getAttribute('data-locked') === "true") {
                    col.removeAttribute('data-locked');
                } else {
                    col.setAttribute('data-locked', 'true');
                }
            });
            palette.appendChild(col);
        });
    } else {
        const cols = palette.querySelectorAll('.col');
        cols.forEach((col, index) => {
            if (col.getAttribute('data-locked') !== "true") {
                const newColor = colors[index];
                col.style.backgroundColor = newColor;
                col.textContent = newColor;
            }
        });
    }
}
```

In this code, we've added a data-index attribute to the color elements so that we can easily identify their position within the palette. We've also updated the click event listener to toggle the data-locked attribute on the clicked color element.

Additionally, we've modified the generatePalette() function to check if there are already color elements on the page. If there are, we only update the background color and text content of unlocked elements (i.e., those without the data-locked attribute set to "true").

Now, when you click a color, it will be locked and won't change when the 'Generate' button is pressed. Clicking a locked color again will unlock it, allowing it to be regenerated.

**Comment by TheMapSmith** [comment]
i haven't tested your code yet, but i'm curious whether you've added a visual indication that a color is locked

**Comment by TheMapSmith** [comment]
# 🤖 

You're right, I didn't add a visual indication for locked colors in my previous response. To provide a visual indication, you can add a CSS class for locked colors and toggle that class when a color is clicked. Here's how to do it:

First, add the following rule to your styles.css file:

```css
.locked {
    opacity: 0.5;
}


This rule will make locked colors semi-transparent to indicate that they are locked.

Next, update the click event listener inside the generatePalette() function in your app.js file to toggle the locked CSS class:

```js
col.addEventListener('click', function () {
    if (col.getAttribute('data-locked') === "true") {
        col.removeAttribute('data-locked');
        col.classList.remove('locked');
    } else {
        col.setAttribute('data-locked', 'true');
        col.classList.add('locked');
    }
});
```

Now, when you click a color to lock it, the locked CSS class will be added to the element, making it semi-transparent. Clicking a locked color again will remove the locked class and restore its opacity.

With these changes, you'll have a visual indication for locked colors, making it easier for users to see which colors are locked and won't be regenerated when the 'Generate' button is pressed.
