### ISSUE TITLE
add lock svg

### ISSUE THREAD

**Issue by TheMapSmith** [TheMapSmith/palettable-two#6]
assume i have a small svg named "fa-lock.svg." Please make the "lock" visual style a clickable button that locks the color, rather than fading it to 50% opacity

**Comment by TheMapSmith** [comment]
# 🤖 

To use an SVG as a lock button that toggles the locked state of a color, you'll need to make the following modifications:

Add the SVG to your color elements.
Update the click event listener to work with the SVG button.
Add CSS styles for the lock button and locked state.

First, include the SVG as a child element of the color column div. Replace the previous click event listener with the following code inside the generatePalette() function in your app.js file:

```js
const lockBtn = document.createElement('img');
lockBtn.src = 'fa-lock.svg';
lockBtn.className = 'lock-btn';
lockBtn.addEventListener('click', function (event) {
    event.stopPropagation(); // Prevent event propagation to the parent element
    if (col.getAttribute('data-locked') === "true") {
        col.removeAttribute('data-locked');
        lockBtn.style.opacity = '0';
    } else {
        col.setAttribute('data-locked', 'true');
        lockBtn.style.opacity = '1';
    }
});
col.appendChild(lockBtn);
```


This code creates an img element with the SVG source, adds a lock-btn class, and sets up a click event listener for the lock button. The locked state is indicated by the opacity of the lock icon.

Next, add the following CSS styles to your styles.css file to position the lock button and style the locked state:

```css
.lock-btn {
    position: absolute;
    top: 5px;
    right: 5px;
    width: 20px;
    height: 20px;
    cursor: pointer;
    opacity: 0;
    transition: opacity 0.3s ease;
}

.col:hover .lock-btn {
    opacity: 0.5;
}

.col[data-locked] .lock-btn {
    opacity: 1;
}
```

These styles position the lock button in the top-right corner of the color element, set its size, and change its opacity based on the locked state and hover interactions.

Now, you'll have an SVG lock button in each color element that toggles the locked state of the color when clicked, instead of using the 50% opacity effect.
