### ISSUE TITLE
Customizable number of colors.

### ISSUE THREAD

**Issue by TheMapSmith** [TheMapSmith/palettable-two#9]
i'd like to add the feature you suggested - Customizable number of colors. The way I'd like it to work is to have a `fa-trash-can.svg` icon remove the color (and reduce the number of colors on regen). also, a `fa-plus.svg` icon to the right side of the colors that adds a new color 

Following #7

**Comment by TheMapSmith** [comment]
# 🤖 

To implement this feature, you need to add the trash can and plus icons, update the generatePalette() function to support a variable number of colors, and handle the click events for the trash can and plus icons. Here's how to do it:

Add the trash can and plus icons to your HTML file:

```html
<button id="add-color" class="btn btn-outline-primary">
    <img src="fa-plus.svg" alt="Add color" />
</button>
```
Update the generatePalette() function in your app.js file to accept a numColors parameter:

```js
function generatePalette(numColors) {
    // ...
    const colors = generateRandomColors(numColors);
    // ...
}
```

Update the initial call to generatePalette() to pass the initial number of colors (e.g., 5) and call it when the page loads:

```js
document.addEventListener('DOMContentLoaded', function () {
    generatePalette(5);
    // ...
});
```
Add event listeners for the trash can and plus icons in your app.js file:

```js
document.getElementById('add-color').addEventListener('click', function () {
    const numColors = document.getElementById('palette').querySelectorAll('.col').length;
    generatePalette(numColors + 1);
});
```

Update the generatePalette() function in your app.js file to handle the trash can icon click event:

```js
const trashBtn = document.createElement('img');
trashBtn.src = 'fa-trash-can.svg';
trashBtn.className = 'trash-btn';
trashBtn.addEventListener('click', function (event) {
    event.stopPropagation();
    col.remove();
    const numColors = document.getElementById('palette').querySelectorAll('.col').length;
    generatePalette(numColors);
});
col.appendChild(trashBtn);
```

Add the following CSS styles to your styles.css file to position the trash can and plus icons:

```css
.trash-btn {
    position: absolute;
    top: 5px;
    left: 5px;
    width: 20px;
    height: 20px;
    cursor: pointer;
    opacity: 0;
    transition: opacity 0.3s ease;
}

.col:hover .trash-btn {
    opacity: 0.5;
}

#add-color {
    position: absolute;
    top: 0;
    right: 0;
    width: 40px;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    border: none;
    background-color: transparent;
}
```

These changes will allow you to add and remove colors using the trash can and plus icons. The palette will regenerate with the new number of colors when you click the 'Generate' button.
